### ISSUE TITLE
Number detection issue

### ISSUE THREAD

**Issue by viraf** [cynapse/SoulverCore#1]
SoulverCore detects a numbers between 1900 to 2100 as a date.

**Comment by zcohan** [comment]
No it doesn't. 
<img width="386" alt="image" src="https://github.com/cynapse/SoulverCore/assets/117823/1c0207c8-4bae-460a-b6c7-b4d06b623491">

Please make your questions very specific and include code where appropriate.

**Comment by viraf** [comment]
https://github.com/cynapse/SoulverCore/assets/1191658/7e25ea6f-3c6e-44b1-9fd4-ffbd70a03146

When we add the term like 1900 apples. It detects as 1900 apples at 1900 January 1. PLease see video

**Comment by apurva** [comment]
Hi @zcohan - to be specific `.find(.date)` does this. Not `calculator.calculate("string")`.

**Comment by zcohan** [comment]
SoulverCore's string parsing functions like `.find(.date)`, are used when you already know the format of the data you're working with. If you ask for a date from "1900 apples", it will do its best to find one and interpret 1900 as a year (because that's what you've asked for). It's like regex.

I'd recommend you instead let SoulverCore decide whether the user meant to use a date or not in a natural language phrase. 

Use a `Calculator` and examine the type of its `EvaluationResult`. If it's a date, do something with it.

<img width="889" alt="image" src="https://github.com/cynapse/SoulverCore/assets/117823/363b9f82-b97c-4586-a50f-f17f447a6349">

**Comment by apurva** [comment]
@zcohan Thanks for the feedback! I tried switching to calculate for the date finding, and now "9 days ago" works, but "2 April" gives no date result, while .find works well in this case. 

To explain our goal here: We are trying to extract one number value and one date value from a single natural language string for example 

"I sold 10 apples yesterday" -> number: 10, date: 3-april-2024 as Date
OR 
"20 apples sold on 1st April" -> number: 10, date: 1-april-2024 as Date

I am facing discrepancies between .find and .calculate in other areas as well, such as

"20 Apples" works with both, but "20Apples" does not return a number using calculate, but find does the job. So currently This is what i have been doing to force a number value out of a string:

```
let calculator = Calculator(customization: .standard)
let result = calculator.calculate(nlString)
if let val = result.stringValue.find(.number) {
    addingEntry?.valueNumber = NSDecimalNumber(decimal: val).doubleValue
} else {
    if let val = nlString.find(.number) {
        addingEntry?.valueNumber = NSDecimalNumber(decimal: val).doubleValue
    } else {
        addingEntry?.valueNumber = 1
    }
}
```

Would love to know what your recommended approach is to achieve our goal. 

p.s. I am a huge fan of Soulver and it has been my default go to calculator app for years! It's a privilege to be able to integrate its capabilities into our app Numerics!

**Comment by zcohan** [comment]
- The calculate function is useful when you're expecting a single result from an expression. 
- The find methods are useful when you know the particular format your data is in. 
- Neither of these are true in your case, and there's no support out of the box for extracting the data you want in a one liner.
- However, you are able to get to get at the underlying parsed expression of tokens, and do your own data extraction from them.

I've attached a sample project demonstrating how to do this, and included some unit tests for the cases you've outlined here. 

Please be aware that the format of the parsed token list is not guaranteed to remain the same in the future. It can and likely will change at any time without warning. It's not part of the stable API, and historically it does change occasionally as SoulverCore's parser becomes more sophisticated to handle more types of expressions. 

For this reason, you may want to consider a different parsing library, or try doing this data extraction in-house.

It might still be less work for you overall to continue to use SoulverCore though, as it handles so many different syntaxes. 

I'd strongly recommend writing your own unit tests though, for all the cases you need to pass, and updating your custom parsing logic in line with any changes to how SoulverCore parses expressions.

**Comment by apurva** [comment]
Thanks for the feedback, and the sample project. I understand that SoulverCore was not designed to do what we are attempting here. While we will explore your recommendations in depth, we are actually quite close to achieving the results we need with the following code to extract a date and a calculated number:

```
let calculator = Calculator(customization: .standard)
let result = calculator.calculate(nlString)
if let val = result.stringValue.find(.number) {
    addingEntry?.valueNumber = NSDecimalNumber(decimal: val).doubleValue
} else {
    if let val = nlString.find(.number) {
        addingEntry?.valueNumber = NSDecimalNumber(decimal: val).doubleValue
    } else {
        addingEntry?.valueNumber = 1
    }
}
            
let dateResult = calculator.calculate(nlString).evaluationResult.datestampValue
if let date = dateResult?.date {
    addingEntry?.valueDate = date
} else {
    if let date = nlString.find(.date) {
        addingEntry?.valueDate = date
    } else {
        addingEntry?.valueDate = Date()
    }
}
```

I am sure this looks like a hack to you the API designer, but it works for our case except for the situation where .find detects 1960 - 2100 as dates. If only there was a way to ask find to not do this, or if it was possible to ask .find to return the NEXT FOUND date, we could be on our way.

**Comment by zcohan** [comment]
The `find` API is working as designed.

If you ask to extract a date from "1900", it will do so (it looks like a year). 

If you asked for a number and then a date, then this would be returned instead:
```
let (number,date) = "1900 bananas April 1st".find(.number, .date)
```

**Comment by apurva** [comment]
Thanks, this helps!
