### ISSUE TITLE
Fuzzy date conversion issue

### ISSUE THREAD

**Issue by viraf** [cynapse/SoulverCore#2]
SoulverCore does not detect "N days ago" as date e.g 9 days ago

**Comment by zcohan** [comment]
Yes it does
<img width="341" alt="image" src="https://github.com/cynapse/SoulverCore/assets/117823/79541d57-aa88-41c8-a61d-7f3a69892722">

**Comment by viraf** [comment]
https://github.com/cynapse/SoulverCore/assets/1191658/1f4b72df-3a3f-42f7-bd1d-4da430ffdfaf

**Comment by apurva** [comment]
@zcohan - Again, to be specific .find(.date) has this issue. Not calculator.calculate("string"). Do you recommend we run a calculate before doing `.find(.date)` ?

**Comment by zcohan** [comment]
I wouldn't use the "find" method here. SoulverCore interprets this phrase as a natural language function that _returns_ a date, but not a date itself that you're scanning for.

Use a Calculator and extract the date from its result, as described in the other thread.
https://github.com/cynapse/SoulverCore/issues/1#issuecomment-2030636037
