### ISSUE TITLE
Invalid archive

### ISSUE THREAD

**Issue by viraf** [cynapse/SoulverCore#3]
![CleanShot 2024-04-01 at 11 35 15@2x](https://github.com/cynapse/SoulverCore/assets/1191658/66ab391f-48ee-4369-8a69-3da53bb5b31d)

When adding the SoulverCore package. The package manager returns an invalid archive message.

**Comment by zcohan** [comment]
The URL is valid and the checksum is correct.

You can debug the problem further on your end, as you have access to the framework file and the Package.swift file. 

One possibility is that the SPM doesn't work with private repositories.

You could try changing the visibility of the repo and see if that solves the problem.

**Comment by viraf** [comment]
I tried changing the visibility to make the repo public, but it did not help. Still getting the same error as the above.

**Comment by zcohan** [comment]
Your guess is as good as mine, I've used the exact same approach here as in the main SoulverCore repo.

Might be a caching issue of some kind in the SPM. 

You could try resetting the cache as described by this comment: https://github.com/apple/swift-package-manager/issues/6635#issuecomment-1994559692

**Comment by viraf** [comment]
Thanks for sharing the link. I did try resetting the cache and also other comment about removing stuff from keychain non have worked so far. Having said that Let us continue to use this repo. We will manually add the framework to our project and not use SPM for now.

**Comment by viraf** [comment]
We are facing a code signing  issue when trying to manually add the framework to the project. 

<img width="344" alt="image" src="https://github.com/cynapse/SoulverCore/assets/1191658/0eed7e39-6abb-44ac-91ba-dae582a5cfe8">

**Comment by zcohan** [comment]
You might need to remove the Gatekeeper quarantine flags from it, as described here.
https://github.com/realm/realm-swift/issues/7003#issuecomment-746710408

**Comment by viraf** [comment]
After much attempts to use the SPM, finally got the SPM working, however only by making the repository public.

**Comment by zcohan** [comment]
Glad to hear this.
